//Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR= "AUTH_ERROR";
export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USERNAME_TAKEN= "USERNAME_TAKEN";
export const USERNAME_AVAILABLE = "USERNAME_AVAILABLE";
//Errors

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//modify accounts
export const UPDATE_SUCCESS= 'UPDATE_SUCCESS';
export  const DELETE_SUCCESS = 'DELETE_SUCCESS';
//errors
export const UPDATE_FAIL = 'UPDATE_FAIL';
export  const DELETE_FAIL = 'DELETE_FAIL';

//Profile stuff
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_FAIL = 'DELETE_PROFILE_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_FAILED = 'PROFILE_FAILED';
//added
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';


//Notifications
export const TURNON_LOGIN_NOTIFICATION = 'TURNON_LOGIN_NOTIFICATION';
export const TURNOFF_LOGIN_NOTIFICATION = 'TURNOFF_LOGIN_NOTIFICATION';

//reg------
export const TURNON_REGISTER_NOTIFICATION = 'TURNON_REGISTER_NOTIFICATION';
export const TURNOFF_REGISTER_NOTIFICATION = 'TURNOFF_REGISTER_NOTIFICATION';

//ANewProduct------
export const TURNON_ADDPRODUCT_NOTIFICATION = 'TURNON_ADDPRODUCT_NOTIFICATION';
export const TURNOFF_ADDPRODUCT_NOTIFICATION = 'TURNOFF_ADDPRODUCT_NOTIFICATION';

//Update-----
export const TURNON_UPDATE_NOTIFICATION = 'TURNON_UPDATE_NOTIFICATION';
export const TURNOFF_UPDATE_NOTIFICATION = 'TURNOFF_UPDATE_NOTIFICATION';

//Delete-----
export const TURNON_DELETE_NOTIFICATION = 'TURNON_DELETE_NOTIFICATION';
export const TURNOFF_DELETE_NOTIFICATION = 'TURNOFF_DELETE_NOTIFICATION';